import fs from "node:fs";import path from "node:path";
const root=process.cwd(), failures=[];
const readJson=file=>{try{return JSON.parse(fs.readFileSync(path.join(root,file),"utf8"))}catch(e){failures.push(`${file}: ${e.message}`);return null}};
const manifest=readJson("module.json"),profiles=readJson("data/roar-profiles.json"),vfx=readJson("data/vfx-manifest.json");readJson("lang/en.json");readJson("lang/ru.json");
if(manifest){for(const [key,value] of Object.entries({id:"roar-impact",version:"1.0.0"}))if(manifest[key]!==value)failures.push(`module.json ${key}`);if(manifest.compatibility?.minimum!=="14"||manifest.compatibility?.verified!=="14")failures.push("Foundry compatibility");for(const file of [...manifest.esmodules,...manifest.styles,...manifest.languages.map(x=>x.path)])if(!fs.existsSync(path.join(root,file)))failures.push(`Missing ${file}`)}
if(profiles){const ids=new Set;for(const p of profiles.profiles){if(ids.has(p.id))failures.push(`Duplicate profile ${p.id}`);ids.add(p.id);for(const file of [p.mainAudio,...p.depthLayers.map(x=>x.file)])if(!fs.existsSync(path.join(root,file)))failures.push(`Missing ${file}`);if(p.depthLayers.length<1||p.depthLayers.length>3)failures.push(`Depth count ${p.id}`)}}
if(vfx)for(const category of Object.keys(vfx.categories))for(const variant of ["a","b"]){const file=`assets/vfx/roar/roar_${category}_${variant}.webm`;if(!fs.existsSync(path.join(root,file)))failures.push(`Missing ${file}`)}
for(const file of fs.readdirSync(path.join(root,"scripts"),{recursive:true}).filter(x=>x.endsWith(".js"))){const text=fs.readFileSync(path.join(root,"scripts",file),"utf8");if(/\beval\s*\(|\bFunction\s*\(/.test(text))failures.push(`Unsafe construct ${file}`);if(/TODO|FIXME|placeholder|mock implementation/i.test(text))failures.push(`Unfinished marker ${file}`)}
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log(`PASS: ${profiles.profiles.length} profiles, ${Object.keys(vfx.categories).length*2} VFX, manifest and references valid.`);
